apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-redis
  labels:
    app: node-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-redis
  template:
    metadata:
      labels:
        app: node-redis
    spec:
      containers:
        - name: node-redis
          imagePullPolicy: Always
          image: arthurescriou/node-redis:1.0.5
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: '8080'
            - name: REDIS_URL
              value: redis://redis:6379
            - name: REDIS_REPLICAS_URL
              value: redis://redis:6379

---


apiVersion: v1
kind: Service
metadata:
  name: node-redis
spec:
  selector:
    app: node-redis
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer

